export default [
    'https://search.smzdm.com?c=faxian&v=a&mx_v=a&f_c=zhi&order=time&s=dolce+gusto+胶囊&max_price=200&brand_id=33743&custom_params=eyJ6aGlQYXJhbSI6NSwicmF0ZVBhcmFtIjowLjcsImRheXMiOjV9',
    'https://search.smzdm.com?c=faxian&v=a&mx_v=a&f_c=zhi&order=time&s=蛋白粉&custom_params=eyJ6aGlQYXJhbSI6MjAsInJhdGVQYXJhbSI6MC42LCJkYXlzIjo1fQ==',
    'https://search.smzdm.com?c=faxian&v=a&mx_v=a&f_c=zhi&order=time&s=碧然德+过滤芯&custom_params=eyJ6aGlQYXJhbSI6MTAsInJhdGVQYXJhbSI6MC43LCJkYXlzIjo1fQ==',
    'https://search.smzdm.com?c=faxian&v=a&mx_v=a&f_c=zhi&order=time&s=鱼油&brand_id=21127&custom_params=eyJ6aGlQYXJhbSI6MTAsInJhdGVQYXJhbSI6MC42LCJkYXlzIjo1fQ==',
    'https://search.smzdm.com?c=faxian&v=a&mx_v=a&f_c=zhi&order=time&s=维生素&brand_id=231&custom_params=eyJ6aGlQYXJhbSI6MTAsInJhdGVQYXJhbSI6MC42LCJkYXlzIjo1fQ==',
    'https://search.smzdm.com?c=faxian&v=a&mx_v=a&f_c=zhi&order=time&s=餐巾纸&min_price=25&cate_id=1515&brand_id=3405&custom_params=eyJ6aGlQYXJhbSI6MjAsInJhdGVQYXJhbSI6MC44LCJkYXlzIjo1fQ==',
    'https://search.smzdm.com?c=faxian&v=a&mx_v=a&f_c=zhi&order=time&s=餐巾纸&min_price=25&cate_id=1515&brand_id=2521&custom_params=eyJ6aGlQYXJhbSI6MjAsInJhdGVQYXJhbSI6MC44LCJkYXlzIjo1fQ==',
    'https://search.smzdm.com?c=faxian&v=a&mx_v=a&f_c=zhi&order=time&s=全棉时代&min_price=80&max_price=200&cate_id=75&custom_params=eyJ6aGlQYXJhbSI6MTAsInJhdGVQYXJhbSI6MC41LCJkYXlzIjo1fQ==',
    'https://search.smzdm.com?c=faxian&v=a&mx_v=a&f_c=zhi&order=time&s=丹碧丝 普通流量&brand_id=3815&custom_params=eyJ6aGlQYXJhbSI6OCwicmF0ZVBhcmFtIjowLjUsImRheXMiOjV9',
    'https://search.smzdm.com?c=faxian&v=a&mx_v=a&f_c=zhi&order=time&s=爱奇艺 京东PLUS&custom_params=eyJ6aGlQYXJhbSI6MjAsInJhdGVQYXJhbSI6MC41LCJkYXlzIjo1fQ==',
    'https://search.smzdm.com?c=faxian&v=a&mx_v=a&f_c=zhi&order=time&s=卷纸 200g&brand_id=2521&custom_params=eyJ6aGlQYXJhbSI6MjAsInJhdGVQYXJhbSI6MC42LCJkYXlzIjo1fQ==',
    'https://search.smzdm.com?c=faxian&v=a&mx_v=a&f_c=zhi&order=time&s=卷纸 200g&brand_id=3405&custom_params=eyJ6aGlQYXJhbSI6MjAsInJhdGVQYXJhbSI6MC42LCJkYXlzIjo1fQ==',
    'https://search.smzdm.com?c=faxian&v=a&mx_v=a&f_c=zhi&order=time&s=咖啡豆 中烘&cate_id=95&custom_params=eyJ6aGlQYXJhbSI6NSwicmF0ZVBhcmFtIjowLjYsImRheXMiOjV9',
    'https://search.smzdm.com?c=faxian&v=a&mx_v=a&f_c=zhi&order=time&s=德运&custom_params=eyJ6aGlQYXJhbSI6MTAsInJhdGVQYXJhbSI6MC42LCJkYXlzIjo1fQ==',
    'https://search.smzdm.com?c=faxian&v=a&mx_v=a&f_c=zhi&order=time&s=牛排&cate_id=95&custom_params=eyJ6aGlQYXJhbSI6NSwicmF0ZVBhcmFtIjowLjYsImRheXMiOjV9',
];
